Repository boostcampwm-2024/web30-stop-troublepainter, pull requests merged in 2024-12, with the labels that each got.

#170 feat: Add random nickname generator
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#172 feat: Add player update functionality
  server/src/game/game.gateway.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#175 feat: Apply random profile images with DiceBear API
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#167 feat: Enhance website metadata and structured JSON data
  client/index.html
  client/public/android-chrome-192x192.png
  client/public/android-chrome-512x512.png
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/site.webmanifest
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#165 chore: Set up Prettier for consistent formatting in core package
  core/.prettierrc
  core/crdt/LWWMap.ts
  core/crdt/LWWRegister.ts
  core/crdt/test/LWWMap.test.ts
  core/crdt/test/LWWRegister.test.ts
  core/package.json
  core/types/game.types.ts
  core/types/socket.types.ts
Labels: ⚙ Setting

#177 fix: Remove duplicate points in CRDT
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
Labels: 🐞 BugFix, 🔨 Refactor

#184 feat: Sort players by score in descending order
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#178 feat: Implement LobbyPage shortcutKey
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatBubbleUI.tsx
  client/src/components/lobby/InviteButton.tsx
  client/src/components/player/PlayerCardList.tsx
  client/src/components/setting/Setting.tsx
  client/src/components/ui/Dropdown.tsx
  client/src/components/ui/Input.tsx
  client/src/constants/shortcutKey.ts
  client/src/hooks/useDropdown.ts
  client/src/hooks/useStartButton.tsx
Labels: ✨ Feature, 💻 FE

#186 feat: Initialize game when player leaves room
  server/src/common/enums/game.status.enum.ts
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#180 feat: Apply game layout background image
  client/src/assets/patterns/background.png
  client/src/assets/patterns/particle-1.png
  client/src/assets/patterns/pattern-0.png
  client/src/assets/patterns/pattern-1.png
  client/src/assets/patterns/pattern-2.png
  client/src/assets/patterns/pattern-3.png
  client/src/assets/patterns/pattern-4.png
  client/src/assets/patterns/pattern-5.png
  client/src/assets/patterns/pattern-6.png
  client/src/assets/patterns/pattern-7.png
  client/src/components/ui/BackgroundCanvas.tsx
  client/src/constants/backgroundConstants.ts
  client/src/layouts/GameLayout.tsx
  client/src/pages/MainPage.tsx
  client/tailwind.config.js
Labels: ✨ Feature, 💻 FE

#187 feat: Change drawing of paint tool coordinates received from socket
  client/src/components/canvas/GameCanvas.tsx
  client/src/components/quiz/QuizStage.tsx
  client/src/constants/canvasConstants.ts
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
Labels: ✨ Feature, 💻 FE

#190 fix: Adjust merge logic to rely on CRDT timestamps
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/types/canvas.types.ts
  core/crdt/LWWMap.ts
  core/types/crdt.types.ts
Labels: 🐞 BugFix, 💻 FE

#191 feat: Implement game result podium page
  client/src/assets/podium.gif
  client/src/components/result/PodiumPlayers.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/usePlayerRanking.ts
  client/src/hooks/useTimeout.ts
  client/src/pages/ResultPage.tsx
  client/src/routes.tsx
  client/src/stores/socket/gameSocket.store.ts
  client/tailwind.config.js
  core/types/game.types.ts
  core/types/socket.types.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#193 fix: Update undo/redo logic to align with CRDT changes
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/hooks/canvas/useDrawingState.ts
  core/crdt/LWWMap.ts
  core/crdt/LWWRegister.ts
  core/types/crdt.types.ts
Labels: 🐞 BugFix, 💻 FE

#194 refactor: Optimize performance with comprehensive component optimization and modular architecture
  client/index.html
  client/package.json
  client/src/App.tsx
  client/src/api/api.config.ts
  client/src/assets/lottie/round-loss.lottie
  client/src/assets/sounds/game-loss.mp3
  client/src/assets/sounds/game-win.mp3
  client/src/components/bgm-button/BackgroundMusicButton.tsx
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatBubbleUI.tsx
  client/src/components/chat/ChatContatiner.tsx
  client/src/components/chat/ChatInput.tsx
  client/src/components/chat/ChatList.tsx
  client/src/components/lobby/InviteButton.tsx
  client/src/components/lobby/StartButton.tsx
  client/src/components/modal/NavigationModal.tsx
  client/src/components/modal/RoleModal.tsx
  client/src/components/modal/RoundEndModal.tsx
  client/src/components/player/PlayerCardList.tsx
  client/src/components/quiz/QuizStage.tsx
  client/src/components/setting/Setting.tsx
  client/src/components/setting/SettingContent.tsx
  client/src/components/setting/SettingItem.tsx
  client/src/components/toast/ToastContainer.tsx
  client/src/components/ui/Dropdown.tsx
  client/src/constants/shortcutKey.ts
  client/src/constants/shortcutKeys.ts
  client/src/hooks/canvas/useDrawingState.ts
  client/src/hooks/socket/useChatSocket.ts
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useCreateRoom.ts
  client/src/hooks/useDropdown.ts
  client/src/hooks/useShortcuts.ts
  client/src/hooks/useStartButton.tsx
  client/src/hooks/useTimer.ts
  client/src/layouts/BrowserNavigationGuard.tsx
  client/src/layouts/GameHeader.tsx
  client/src/layouts/GameLayout.tsx
  client/src/pages/GameRoomPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  client/src/stores/socket/socket.config.ts
  client/src/stores/timer.store.ts
  client/src/utils/checkProduction.ts
  client/src/utils/soundManager.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 🔨 Refactor, 💻 FE

#198 fix: Add retry logic for fetching words in startGame
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: 🐞 BugFix, 💻 BE

#200 feat: Improve CDN migration and nickname generation system
  client/src/assets/logo/main-logo.png
  client/src/assets/logo/side-logo.png
  client/src/assets/patterns/background.png
  client/src/assets/sounds/background-music.mp3
  client/src/components/ui/Logo.tsx
  client/src/constants/cdn.ts
  client/src/hooks/useBackgroundMusic.ts
  client/tailwind.config.js
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 FE

#201 refactor: Modify unit tests for CRDT LWW
  core/crdt/test/LWWMap.test.ts
  core/crdt/test/LWWRegister.test.ts
  core/vitest.config.ts
Labels: 🔨 Refactor, ✅ Test

#203 feat: Implement game logic and UI
  client/src/components/modal/RoundEndModal.tsx
  client/src/components/quiz/QuizStage.tsx
  client/src/components/setting/Setting.tsx
  client/src/layouts/GameLayout.tsx
  client/src/pages/ResultPage.tsx
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#143 feat: User Experience Optimization Code Merge about Drawing
  client/src/components/canvas/CanvasUI.tsx
  client/src/components/canvas/GameCanvas.tsx
  client/src/handlers/canvas/cursorInOutHandler.ts
  client/src/hooks/canvas/useDrawingOperation.ts
Labels: ✨ Feature, 💻 FE

#199 feat: Implements help component and prevents dragging
  client/package.json
  client/src/assets/left.svg
  client/src/assets/lottie/help/fifth.json
  client/src/assets/lottie/help/first.json
  client/src/assets/lottie/help/fourth.json
  client/src/assets/lottie/help/second.json
  client/src/assets/lottie/help/third.json
  client/src/assets/right.svg
  client/src/components/chat/ChatBubbleUI.tsx
  client/src/components/modal/HelpRollingModal.tsx
  client/src/components/ui/HelpContainer.tsx
  client/src/components/ui/Modal.tsx
  client/src/index.css
  client/src/layouts/RootLayout.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 💻 FE

#204 feat: Implement WebSocket-based Playwright tests
  core/crdt/test/drawing-utils.ts
  core/crdt/test/random-drawing.test.ts
  core/crdt/test/test-types.ts
  core/crdt/test/test-utils.ts
  core/package.json
  core/playwright.config.ts
  pnpm-lock.yaml
Labels: ⚙ Setting, ✅ Test
