Repository boostcampwm-2024/web30-stop-troublepainter, pull requests merged in 2024-11, with the labels that each got.

#17 feat: Implement design system with color and font configurations
  client/index.html
  client/tailwind.config.js
Labels: ⚙ Setting, FE

#18 feat: Implement main logo component
  client/src/App.tsx
  client/src/assets/logo/main-logo.png
  client/src/assets/logo/side-logo.png
  client/src/components/ui/Logo.tsx
Labels: ✨ Feature, 🎨 Html&css, FE

#24 feat: Implement UserInfoCard component with desktop and mobile mode
  client/src/App.tsx
  client/src/assets/crown-first.png
  client/src/assets/profile-placeholder.png
  client/src/components/ui/UserInfoCard.stories.tsx
  client/src/components/ui/UserInfoCard.tsx
  client/src/types/userInfo.types.ts
  client/src/utils/getCrownImage.ts
  client/tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css, FE

#19 feat: Implement Input component
  client/src/components/ui/Input.tsx
Labels: ✨ Feature, 🎨 Html&css, FE

#20 feat: Implement resuable ChatBubble component
  client/src/components/ui/ChatBubble.tsx
Labels: ✨ Feature, 🎨 Html&css, FE

#25 feat: Implement reusable Modal component
  client/src/components/ui/Modal.tsx
Labels: ✨ Feature, 🎨 Html&css, FE

#30 feat: Implement reusable Dropdown component
  client/src/assets/arrow.svg
  client/src/components/ui/Dropdown.tsx
  client/src/hooks/useDropdown.ts
Labels: ✨ Feature, 🎨 Html&css, FE

#31 feat: Implement QuizTitle component
  client/src/App.tsx
  client/src/assets/big-timer.gif
  client/src/assets/small-timer.gif
  client/src/assets/small-timer.png
  client/src/components/ui/QuizTitle.tsx
Labels: ✨ Feature, 🎨 Html&css, FE

#28 feat: Implement Chatting component
  client/src/components/chat/ChatBubbleUI.tsx
  client/src/components/chat/Chatting.tsx
  client/src/components/ui/Input.tsx
Labels: ✨ Feature, 🎨 Html&css, FE

#34 feat: Implement headless auto-closing modal component
  client/src/App.tsx
  client/src/components/ui/Modal.tsx
  client/src/hooks/useModal.ts
  client/src/utils/timer.ts
Labels: ✨ Feature, 🎨 Html&css, FE

#35 feat: Implement canvas drawing system with role-based permissions
  client/src/App.tsx
  client/src/assets/bucket-icon.svg
  client/src/assets/pen-icon.svg
  client/src/assets/redo-icon.svg
  client/src/components/canvas/CanvasUI.tsx
  client/src/components/canvas/GameCanvasExample.tsx
  client/src/components/canvas/InkGauge.tsx
  client/src/hooks/useDrawing.ts
  client/src/types/userInfo.types.ts
Labels: ✨ Feature, 🎨 Html&css, FE

#33 feat: Implement Canvas Drawing Event (Pen Mode)
  client/src/components/canvas/MainCanvas.tsx
  client/src/stores/useCanvasStore.ts
  client/src/types/canvas.types.ts
Labels: ✨ Feature, FE

#40 feat: Implement RootLayout and router structure
  client/package.json
  client/pnpm-lock.yaml
  client/src/App.tsx
  client/src/components/ui/Logo.tsx
  client/src/layouts/GameLayout.tsx
  client/src/layouts/RootLayout.tsx
  client/src/main.tsx
  client/src/pages/ExamplePage.tsx
  client/src/pages/MainPage.tsx
  client/src/routes/index.tsx
  client/tailwind.config.js
Labels: ✨ Feature, 🎨 HTML&CSS, ⚙ Setting, FE

#44 feat: Add Storybook workflow
  .github/workflows/storybook-ci-cd.yml
  .github/workflows/storybook-preview-ci-cd.yml
  client/typedoc.json
Labels: 🌏 Deploy, FE

#39 feat: Implements change color, line-width, pen-mode function
  client/src/components/canvas/CanvasToolbar.tsx
  client/src/components/canvas/DrawingArea.tsx
  client/src/components/canvas/MainCanvas.tsx
  client/src/constants/canvasConstants.ts
  client/src/stores/useCanvasStore.ts
  client/src/types/canvas.types.ts
Labels: ✨ Feature, FE

#41 feat: Implements Paint Tool
  client/src/components/canvas/MainCanvas.tsx
  client/src/types/canvas.types.ts
  client/src/utils/hexToRGBA.ts
Labels: ✨ Feature, FE

#43 feat: Implement coordinate adjustment based on canvas size
  client/src/components/canvas/MainCanvas.tsx
  client/src/constants/canvasConstants.ts
  client/src/hooks/useCoordinateScale.ts
Labels: ✨ Feature, FE

#38 feat: Implement Setting component
  client/src/components/setting/Setting.tsx
  client/src/components/ui/Dropdown.tsx
  client/src/constants/setting.ts
  client/src/types/setting.types.ts
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#50 fix: Fix mistakenly merged faulty code
  client/src/components/canvas/MainCanvas.tsx
  client/src/constants/canvasConstants.ts
  client/src/hooks/useCoordinateScale.ts
Labels: 🐞 BugFix, FE

#46 feat: Implement Main page & Implement transitions with pixel animations and hover effects
  client/src/components/ui/Button.tsx
  client/src/components/ui/PixelTransitionContainer.tsx
  client/src/hooks/usePageTransition.ts
  client/src/layouts/RootLayout.tsx
  client/src/pages/ExamplePage.tsx
  client/src/pages/MainPage.tsx
  client/src/routes/index.tsx
  client/tailwind.config.js
Labels: ✨ Feature, 🎨 HTML&CSS, FE

#47 docs: Add Modal, Button, Input, Dropdown component stories
  client/.storybook/preview.ts
  client/src/components/ui/Button.stories.tsx
  client/src/components/ui/Dropdown.stories.tsx
  client/src/components/ui/Input.stories.tsx
  client/src/components/ui/Modal.stories.tsx
  client/src/components/ui/Modal.tsx
  client/src/hooks/useModal.ts
Labels: 📃 Docs, FE

#58 docs: Add Logo, QuizTitle, UserInfoCard, ChatBubbleUI component stories
  client/src/components/chat/ChatButtle.stories.tsx
  client/src/components/ui/Button.stories.tsx
  client/src/components/ui/Dropdown.stories.tsx
  client/src/components/ui/Input.stories.tsx
  client/src/components/ui/Logo.stories.tsx
  client/src/components/ui/Modal.stories.tsx
  client/src/components/ui/QuizTitle.stories.tsx
  client/src/components/ui/QuizTitle.tsx
  client/src/components/ui/UserInfoCard.stories.tsx
  client/src/components/ui/UserInfoCard.tsx
  client/src/stories/Button.stories.ts
  client/src/stories/Button.tsx
  client/src/stories/Header.stories.ts
  client/src/stories/Header.tsx
  client/src/stories/Page.stories.ts
  client/src/stories/Page.tsx
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: 📃 Docs, 💻 FE

#64 feat: Implement CRDT register and map with associated types
  client/src/core/crdt.types.ts
  client/src/core/crdt/LWWMap.ts
  client/src/core/crdt/LWWRegister.ts
Labels: ✨ Feature, 💻 FE

#66 feat: Implement initial room system
  server/package.json
  server/pnpm-lock.yaml
  server/src/app.module.ts
  server/src/drawing/drawing.gateway.spec.ts
  server/src/drawing/drawing.gateway.ts
  server/src/drawing/drawing.interface.ts
  server/src/drawing/drawing.module.ts
  server/src/redis/redis.module.ts
  server/src/redis/redis.service.spec.ts
  server/src/redis/redis.service.ts
  server/src/room/room.gateway.spec.ts
  server/src/room/room.gateway.ts
  server/src/room/room.interface.ts
  server/src/room/room.module.ts
  server/src/room/room.service.spec.ts
  server/src/room/room.service.ts
Labels: ✨ Feature, 💻 BE

#69 feat: Impement Game match room
  client/src/components/canvas/CanvasUI.tsx
  client/src/components/canvas/GameCanvasExample.tsx
  client/src/components/canvas/InkGauge.tsx
  client/src/components/chat/ChatBubbleUI.tsx
  client/src/components/chat/Chatting.tsx
  client/src/components/ui/QuizTitle.tsx
  client/src/components/ui/UserInfoCard.tsx
  client/src/layouts/GameLayout.tsx
  client/src/layouts/RootLayout.tsx
  client/src/main.tsx
  client/src/pages/GameRoomPage.tsx
  client/src/routes.tsx
  client/src/routes/index.tsx
  client/src/types/chat.types.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#67 test: Add unit tests for LWW register and LWW Map
  client/package.json
  client/pnpm-lock.yaml
  client/src/core/test/LWWMap.test.ts
  client/src/core/test/LWWRegister.test.ts
  client/tsconfig.app.json
  client/vite.config.ts
Labels: ✅ Test, 💻 FE

#74 feat: Implement room creation/join feature
  server/.env.example
  server/.eslintrc.js
  server/.prettierrc
  server/package.json
  server/pnpm-lock.yaml
  server/src/app.controller.spec.ts
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/drawing/drawing.gateway.spec.ts
  server/src/drawing/drawing.gateway.ts
  server/src/drawing/drawing.interface.ts
  server/src/drawing/drawing.module.ts
  server/src/game/game.controller.spec.ts
  server/src/game/game.controller.ts
  server/src/game/game.gateway.spec.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/game/game.service.spec.ts
  server/src/game/game.service.ts
  server/src/redis/redis.service.spec.ts
  server/src/redis/redis.service.ts
  server/src/room/room.gateway.spec.ts
  server/src/room/room.gateway.ts
  server/src/room/room.interface.ts
  server/src/room/room.module.ts
  server/src/room/room.service.spec.ts
  server/src/room/room.service.ts
  server/src/types/game.types.ts
  server/src/utils/generateId.ts
  server/test/app.e2e-spec.ts
Labels: ✨ Feature, 💻 BE

#80 feat : Implement DrawGateway and DrawModule for real-time drawing feature
  server/src/app.module.ts
  server/src/draw/draw.gateway.spec.ts
  server/src/draw/draw.gateway.ts
  server/src/draw/draw.module.ts
  server/src/game/game.gateway.ts
Labels: ✨ Feature, 💻 BE

#85 feat: Setting up Socket.IO infrastructure in client
  client/.env.example
  client/package.json
  client/pnpm-lock.yaml
  client/src/core/socket/gameSocket.store.ts
  client/src/core/socket/socket.config.ts
  client/src/core/socket/socket.store.ts
  client/src/core/socket/socket.types.ts
  client/src/core/socket/useGameSocket.ts
  client/src/layouts/GameLayout.tsx
  client/src/pages/GameRoomPage.tsx
  client/src/pages/LobbyPage.tsx
  client/src/pages/MainPage.tsx
  client/src/routes.tsx
Labels: 📬 API, ✨ Feature, 💻 FE

#87 refactor: Improve code structure with error handling
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.module.ts
  server/src/chat/chat.repository.ts
  server/src/chat/chat.service.spec.ts
  server/src/chat/chat.service.ts
  server/src/common/enums/game.status.enum.ts
  server/src/common/enums/socket.error-code.enum.ts
  server/src/common/types/game.types.ts
  server/src/draw/draw.gateway.ts
  server/src/exceptions/game.exception.ts
  server/src/filters/ws-exception.filter.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
Labels: 🔨 Refactor, 💻 BE

#82 feat: Implement LobbyPage
  client/src/components/chat/ChatList.tsx
  client/src/components/setting/Setting.tsx
  client/src/components/ui/Dropdown.stories.tsx
  client/src/components/ui/Dropdown.tsx
  client/src/constants/setting.ts
  client/src/layouts/GameLayout.tsx
  client/src/pages/GameRoomPage.tsx
  client/src/pages/LobbyPage.tsx
  client/src/types/setting.types.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#88 feat: Enhance real-time canvas system with unified data structure and socket integration
  client/src/components/canvas/GameCanvasExample.tsx
  client/src/components/setting/Setting.tsx
  client/src/components/ui/UserInfoCard.stories.tsx
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useCoordinateScale.ts
  client/src/hooks/useDrawing.ts
  client/src/layouts/GameLayout.tsx
  client/src/pages/ExamplePage.tsx
  client/src/pages/ExamplePageCanvasOnly.tsx
  client/src/pages/GameRoomPage.tsx
  client/src/pages/LobbyPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  client/src/stores/socket/socket.config.ts
  client/src/stores/socket/socket.store.ts
  client/src/types/canvas.types.ts
  client/src/types/drawingShared.types.ts
  client/src/types/gameShared.types.ts
  client/src/types/socket.types.ts
  client/src/types/socketShared.types.ts
  client/src/utils/getCrownImage.ts
Labels: 📬 API, ✨ Feature, 💻 FE

#91 chore: Migrate project to monorepo structure
  .github/workflows/server-ci-cd.yml
  .github/workflows/storybook-ci-cd.yml
  .github/workflows/storybook-preview-ci-cd.yml
  .github/workflows/typedoc-ci-cd.yml
  Dockerfile
  client/.storybook/main.ts
  client/package.json
  client/src/components/canvas/GameCanvasExample.tsx
  client/src/components/setting/Setting.tsx
  client/src/components/ui/UserInfoCard.stories.tsx
  client/src/components/ui/UserInfoCard.tsx
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useCoordinateScale.ts
  client/src/hooks/useDrawing.ts
  client/src/pages/ExamplePage.tsx
  client/src/pages/ExamplePageCanvasOnly.tsx
  client/src/pages/GameRoomPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  client/src/stores/socket/socket.config.ts
  client/src/types/drawingShared.types.ts
  client/src/types/socket.types.ts
  client/src/utils/getDrawPoint.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/typedoc.json
  client/vite.config.ts
  core/crdt/LWWMap.ts
  core/crdt/LWWRegister.ts
  core/crdt/index.ts
  core/crdt/test/LWWMap.test.ts
  core/crdt/test/LWWRegister.test.ts
  core/index.ts
  core/package.json
  core/tsconfig.json
  core/tsup.config.ts
  core/types/crdt.types.ts
  core/types/game.types.ts
  core/types/index.ts
  core/types/socket.types.ts
  core/vitest.config.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  server/Dockerfile
  server/package.json
  tsconfig.base.json
  typedoc.json
Labels: 🌏 Deploy, ⚙ Setting

#95 feat: Implement room settings update
  server/src/game/game.gateway.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#96 feat: Implement real-time chat system with Socket.IO
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatList.tsx
  client/src/components/ui/PlayerCard.stories.tsx
  client/src/components/ui/PlayerCard.tsx
  client/src/hooks/socket/useChatSocket.ts
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useScrollToBottom.ts
  client/src/layouts/GameLayout.tsx
  client/src/pages/ExamplePage.tsx
  client/src/stores/socket/chatSocket.store.ts
  client/src/stores/socket/gameSocket.store.ts
  client/src/stores/socket/socket.config.ts
  client/src/utils/getCrownImage.ts
  client/src/utils/playerIdStorage.ts
  core/types/socket.types.ts
Labels: 📬 API, ✨ Feature, 💻 FE

#97 fix: Resolve duplicate timers and reconnection timing issues in handleDisconnect
  server/src/game/game.gateway.ts
Labels: 🐞 BugFix, 💻 BE

#101 feat: Delete ready system and add game start system
  client/src/components/chat/ChatBubbleUI.tsx
  client/src/components/player/PlayerCardList.tsx
  client/src/components/ui/Input.tsx
  client/src/components/ui/PlayerCard.tsx
  client/src/hooks/socket/useChatSocket.ts
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/layouts/GameLayout.tsx
  client/src/pages/ExamplePage.tsx
  client/src/pages/LobbyPage.tsx
  client/src/routes.tsx
  client/src/stores/socket/gameSocket.store.ts
  core/types/game.types.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#106 feat: Implement socket connection in Setting component for real-time updates
  client/src/components/setting/Setting.tsx
  client/src/handlers/socket/gameSocket.handler.ts
  client/src/hooks/socket/useGameSocket.ts
Labels: ✨ Feature, 💻 FE

#111 feat: Improve socket event handling and code organization
  server/src/chat/chat.gateway.ts
  server/src/common/types/game.types.ts
  server/src/game/game.gateway.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
  server/src/redis/redis.service.ts
Labels: 🔨 Refactor, 💻 BE

#113 feat: Add round timer functionality
  server/src/common/enums/game.status.enum.ts
  server/src/common/services/timer.service.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#115 feat: Implement game start logic and role distribution
  client/index.html
  client/src/App.tsx
  client/src/components/modal/RoleModal.tsx
  client/src/components/player/PlayerCardList.tsx
  client/src/components/ui/Modal.tsx
  client/src/components/ui/PlayerCard.tsx
  client/src/constants/gameConstant.ts
  client/src/handlers/socket/gameSocket.handler.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/pages/GameRoomPage.tsx
  client/src/pages/LobbyPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  client/src/types/game.types.ts
  core/types/game.types.ts
Labels: ✨ Feature, 💻 FE

#116 feat: Add Toast system with accessibility and animations
  client/src/App.tsx
  client/src/components/toast/ToastContainer.tsx
  client/src/components/ui/Toast.tsx
  client/src/stores/toast.store.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#117 fix: Fix undo/redo functionality issues during CRDT integration
  client/src/components/canvas/GameCanvas.tsx
  client/src/hooks/useDrawing.ts
Labels: 🐞 BugFix

#121 feat: Implement CLOVA Studio integration for drawing word generation
  .github/workflows/server-ci-cd.yml
  pnpm-lock.yaml
  server/package.json
  server/src/common/clova-client.ts
  server/src/common/enums/game.status.enum.ts
  server/src/game/game.gateway.ts
  server/src/game/game.module.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#127 feat: Add timerSync handler to synchronize timer with server
  client/src/hooks/socket/useGameSocket.ts
  client/src/pages/GameRoomPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  client/src/utils/checkTimerDifference.ts
  core/types/socket.types.ts
Labels: ✨ Feature, 💻 FE

#126 feat: Implement game invitation system with enhanced lobby structure
  client/src/components/lobby/InviteButton.tsx
  client/src/components/lobby/StartButton.tsx
  client/src/components/setting/Setting.tsx
  client/src/components/toast/ToastContainer.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useStartButton.tsx
  client/src/pages/LobbyPage.tsx
  client/src/stores/socket/gameSocket.store.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🔨 Refactor, 💻 FE

#128 refactor: Split useDrawing hook into layered architecture
  client/src/components/canvas/GameCanvas.tsx
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/hooks/canvas/useDrawingState.ts
  client/src/hooks/useDrawing.ts
  client/src/stores/toast.store.ts
  client/src/types/canvas.types.ts
  core/types/crdt.types.ts
Labels: 🔨 Refactor

#130 feat: Implement answer checking system
  server/src/exceptions/game.exception.ts
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#136 design & refactor: Enhance PlayerCard UI for self-identification and improve component structure
  client/src/components/player/PlayerCardList.tsx
  client/src/components/ui/PlayerCard.tsx
  client/src/components/ui/player-card/PlayerCard.stories.tsx
  client/src/components/ui/player-card/PlayerCard.tsx
  client/src/components/ui/player-card/PlayerInfo.tsx
  client/src/components/ui/player-card/PlayerProfile.tsx
  client/src/components/ui/player-card/PlayerStatus.tsx
  client/src/stores/socket/socket.config.ts
  client/src/utils/getCrownImage.ts
Labels: 🎨 HTML&CSS, 🔨 Refactor, 💻 FE

#137 feat: Implement game round management
  server/src/common/enums/game.timer.enum.ts
  server/src/game/game.gateway.ts
  server/src/game/game.service.ts
Labels: ✨ Feature, 💻 BE

#142 feat: Add drawing broadcast to all players
  server/src/game/game.gateway.ts
Labels: ✨ Feature, 💻 BE

#144 feat: Implement timer and RoundEnd Modal
  client/src/components/chat/Chat.tsx
  client/src/components/modal/RoleModal.tsx
  client/src/components/modal/RoundEndModal.tsx
  client/src/components/player/PlayerCardList.tsx
  client/src/components/setting/Setting.tsx
  client/src/handlers/socket/gameSocket.handler.ts
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useStartButton.tsx
  client/src/hooks/useTimer.ts
  client/src/pages/GameRoomPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  core/types/game.types.ts
  core/types/socket.types.ts
Labels: ✨ Feature, 💻 FE

#146 feat: Enhance navigation(refresh, popstate, URL etc.) handling and accessibility in game layout
  client/src/components/modal/NavigationModal.tsx
  client/src/components/ui/Modal.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/index.css
  client/src/layouts/BrowserNavigationGuard.tsx
  client/src/layouts/GameHeader.tsx
  client/src/layouts/GameLayout.tsx
  client/src/stores/navigationModal.store.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#151 feat: Implement audio system with background music and sound effects
  client/src/assets/sound-logo.svg
  client/src/assets/sounds/background-music.mp3
  client/src/assets/sounds/entry-sound-effect.mp3
  client/src/components/bgm-button/BackgroundMusicButton.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/hooks/useBackgroundMusic.ts
  client/src/layouts/RootLayout.tsx
  client/src/utils/soundManager.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 💻 FE

#157 feat: Enhance game UX with Lottie animations
  client/package.json
  client/src/App.tsx
  client/src/api/api.config.ts
  client/src/assets/lottie/game-win.lottie
  client/src/assets/lottie/loading.lottie
  client/src/assets/lottie/round-loss.lottie
  client/src/assets/lottie/round-win.lottie
  client/src/components/modal/RoundEndModal.tsx
  client/src/layouts/GameLayout.tsx
  client/src/types/declarations.d.ts
  client/vite.config.ts
  pnpm-lock.yaml
Labels: ✨ Feature, 🎨 HTML&CSS, ⚙ Setting, 💻 FE

#161 fix: Update navigation logic and fix URL handling
  client/src/layouts/BrowserNavigationGuard.tsx
  client/src/layouts/RootLayout.tsx
  client/src/pages/MainPage.tsx
Labels: 🐞 BugFix, 💻 FE

#162 feat: Send and expose drawing data to spectators when the timer ends
  client/src/components/canvas/GameCanvas.tsx
  client/src/handlers/socket/gameSocket.handler.ts
  client/src/hooks/canvas/useDrawing.ts
  client/src/hooks/canvas/useDrawingOperation.ts
  client/src/hooks/canvas/useDrawingState.ts
  client/src/hooks/socket/useDrawingSocket.ts
  client/src/pages/GameRoomPage.tsx
  core/types/socket.types.ts
Labels: ✨ Feature, 💻 FE

#155 fix: Fix player UI
  client/src/components/player/PlayerCardList.tsx
  client/src/components/ui/player-card/PlayerProfile.tsx
  client/src/components/ui/player-card/PlayerStatus.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/stores/socket/gameSocket.store.ts
Labels: 🐞 BugFix, 🎨 HTML&CSS, 💻 FE

#153 feat: Implement global state initialization for round end and game end
  client/src/components/setting/Setting.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/stores/socket/gameSocket.store.ts
Labels: ✨ Feature, 💻 FE

#159 refactor: Improve room and player validation
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.repository.ts
  server/src/chat/chat.service.ts
  server/src/drawing/drawing.gateway.ts
  server/src/drawing/drawing.module.ts
  server/src/drawing/drawing.repository.ts
  server/src/drawing/drawing.service.ts
  server/src/exceptions/game.exception.ts
  server/src/game/game.gateway.ts
  server/src/game/game.repository.ts
  server/src/game/game.service.ts
  server/src/redis/redis.service.ts
Labels: 🐞 BugFix, 💻 BE

#158 feat: Apply MainPage background pattern
  client/src/assets/patterns/particle-1.png
  client/src/assets/patterns/pattenrs.ts
  client/src/assets/patterns/pattern-0.png
  client/src/assets/patterns/pattern-1.png
  client/src/assets/patterns/pattern-2.png
  client/src/assets/patterns/pattern-3.png
  client/src/assets/patterns/pattern-4.png
  client/src/assets/patterns/pattern-5.png
  client/src/assets/patterns/pattern-6.png
  client/src/assets/patterns/pattern-7.png
  client/src/components/ui/BackgroundCanvas.tsx
  client/src/constants/backgroundConstants.ts
  client/src/pages/MainPage.tsx
Labels: ✨ Feature, 💻 FE

#163 feat: Add PlayerRole/RoomStatus-based UI Handling
  client/src/components/chat/Chat.tsx
  client/src/components/modal/RoundEndModal.tsx
  client/src/components/quiz/QuizStage.tsx
  client/src/components/ui/QuizTitle.tsx
  client/src/hooks/socket/useGameSocket.ts
  client/src/pages/GameRoomPage.tsx
  client/src/stores/socket/gameSocket.store.ts
  core/types/socket.types.ts
Labels: ✨ Feature, 💻 FE
